spring.datasource.url=jdbc:sqlserver://localhost\\mssqlserver;databaseName=master;portNumber=1433;encrypt=true;trustServerCertificate=true
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}