spring.application.name=personal_registrar
spring.application.version=0.0.1

spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true

spring.liquibase.contexts=dev

logging.file.name=logs/app.log
logging.file.path=logs
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE

server.error.include-message=always
server.error.include-binding-errors=always